language: java

before_install:
  - chmod +x "ci/run.sh"
  - sudo apt-get update                                # run update before installing anything
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)
  - mkdir ~/haxelib                                    # create a folder for installing haxelib
  - haxelib setup ~/haxelib
  - haxelib install HaxePunk                           # install haxepunk
  - echo yes | haxelib run HaxePunk setup
  - lime setup android
  - lime test neko
  - mkdir bin                                          # create an output folder if needed
script: "ci/run.sh"
